name: CI
on: pull_request
jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-env: ["development", "production"]
    env:
      NODE_ENV: ${{ matrix.node-env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - run: bun install

      - run: bun lint
        if: ${{ matrix.node-env == 'development' }}

      - run: bun test
        if: ${{ matrix.node-env == 'development' }}
